### ISSUE TITLE
Either a bug or I didn't set something up right

### ISSUE THREAD

**Issue by niacdoial** [maubot/karma#9]
Hello!
I recently installed maubot and tried to reverse-engineer Karma to hopefully make my own bots,
but when I used a "!karma up" as a reply, nothing seemed to happen, and the log only said
```
[2019-03-21 22:09:13,403] [ERROR@maubot.client.@niacdobot413:matrix.org] Failed to run handler
Traceback (most recent call last):
  File "/path/to/maubot-venv/lib/python3.6/site-packages/mautrix/client/client.py", line 108, in call_handlers
    await handler(event)
  File "/path/to/maubot-venv/lib/python3.6/site-packages/maubot/handlers/command.py", line 85, in __call__
    ok, res = await self.__call_subcommand__(evt, call_args, remaining_val)
  File "/path/to/maubot-venv/lib/python3.6/site-packages/maubot/handlers/command.py", line 102, in __call_subcommand__
    remaining_val=remaining_val)
  File "/path/to/maubot-venv/lib/python3.6/site-packages/maubot/handlers/command.py", line 94, in __call__
    return await self.__mb_func__(evt, **call_args)
TypeError: upvote() missing 1 required positional argument: 'evt'
```
I was using a fresh version of Karma (76f65eb9d3bf043126cc91904ca4df74ec24abbe), with a python 3.6 virtualenv, and the PyPI version of maubot (maubot 0.1.0.dev15)
(on ubuntu 18.04 if this is of any relevance)

Thanks in advance, and I hope I don't bother you too much with this, if the problem is on my part.
Have a nice day

**Comment by tulir** [comment]
The pypi build is outdated currently. You can probably update with `pip install --upgrade https://github.com/maubot/maubot/tarball/master#egg=maubot`
